import { useState, useEffect } from 'react';
import { X } from 'lucide-react';
import { api } from '../../api';

interface Props { hypothesis: any; onClose: () => void; onSave: () => void; }
export default function HypothesisForm({ hypothesis, onClose, onSave }: Props) {
  const [projects, setProjects] = useState<any[]>([]);
  const [form, setForm] = useState({ project_id: '', statement: '', confidence_score: '0.70', status: 'proposed', supporting_evidence: '', contradicting_evidence: '', generated_by: 'human' });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => {
    api.getProjects().then(setProjects).catch(console.error);
    if (hypothesis) setForm({ project_id: hypothesis.project_id?.toString()||'', statement: hypothesis.statement||'', confidence_score: hypothesis.confidence_score?.toString()||'0.70', status: hypothesis.status||'proposed', supporting_evidence: hypothesis.supporting_evidence||'', contradicting_evidence: hypothesis.contradicting_evidence||'', generated_by: hypothesis.generated_by||'human' });
  }, [hypothesis]);
  const set = (k: string, v: string) => setForm(f => ({ ...f, [k]: v }));
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault(); setSaving(true); setError('');
    try {
      const payload = { ...form, project_id: parseInt(form.project_id), confidence_score: parseFloat(form.confidence_score) };
      if (hypothesis) await api.updateHypothesis(hypothesis.id, payload); else await api.createHypothesis(payload);
      onSave();
    } catch (err: any) { setError(err.message); setSaving(false); }
  };

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200"><h2 className="font-bold text-gray-900">{hypothesis ? 'Edit Hypothesis' : 'New Hypothesis'}</h2><button onClick={onClose}><X className="w-5 h-5 text-gray-400" /></button></div>
        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          {error && <div className="p-3 bg-red-50 text-red-700 rounded-lg text-sm">{error}</div>}
          <div className="grid grid-cols-2 gap-4">
            <div><label className="block text-sm font-medium text-gray-700 mb-1">Project *</label><select required value={form.project_id} onChange={e => set('project_id', e.target.value)} className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none"><option value="">Select project</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></div>
            <div><label className="block text-sm font-medium text-gray-700 mb-1">Generated By</label><select value={form.generated_by} onChange={e => set('generated_by', e.target.value)} className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none"><option value="human">Human</option><option value="ai">AI</option></select></div>
            <div className="col-span-2"><label className="block text-sm font-medium text-gray-700 mb-1">Hypothesis Statement *</label><textarea required value={form.statement} onChange={e => set('statement', e.target.value)} rows={3} className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none resize-none" /></div>
            <div><label className="block text-sm font-medium text-gray-700 mb-1">Confidence (0-1)</label><input type="number" step="0.01" min="0" max="1" value={form.confidence_score} onChange={e => set('confidence_score', e.target.value)} className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none" /></div>
            <div><label className="block text-sm font-medium text-gray-700 mb-1">Status</label><select value={form.status} onChange={e => set('status', e.target.value)} className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none">{['proposed','testing','validated','rejected'].map(s => <option key={s} value={s}>{s}</option>)}</select></div>
            <div className="col-span-2"><label className="block text-sm font-medium text-gray-700 mb-1">Supporting Evidence</label><textarea value={form.supporting_evidence} onChange={e => set('supporting_evidence', e.target.value)} rows={2} className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none resize-none" /></div>
            <div className="col-span-2"><label className="block text-sm font-medium text-gray-700 mb-1">Contradicting Evidence</label><textarea value={form.contradicting_evidence} onChange={e => set('contradicting_evidence', e.target.value)} rows={2} className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none resize-none" /></div>
          </div>
          <div className="flex gap-3 pt-2"><button type="button" onClick={onClose} className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg text-sm font-medium hover:bg-gray-50">Cancel</button><button type="submit" disabled={saving} className="flex-1 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white rounded-lg text-sm font-medium">{saving ? 'Saving...' : hypothesis ? 'Update' : 'Create'}</button></div>
        </form>
      </div>
    </div>
  );
}
